In [18]:
import pandas as pd
df_fert = pd.read_csv("fertilizer.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'fertilizer.csv'

In [ ]:
df_fert.head()

,District_Name,Soil_color,Nitrogen,Phosphorus,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer,Link
0,Kolhapur,Black,75,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
1,Kolhapur,Black,80,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
2,Kolhapur,Black,85,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
3,Kolhapur,Black,90,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
4,Kolhapur,Black,95,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo

In [ ]:
df_fert = df_fert.drop(columns=["District_Name", "Link"])

In [ ]:
df_fert["Crop"] = df_fert["Crop"].str.replace(" ", "")
df_fert["Crop"] = df_fert["Crop"].str.lower().str.strip()

In [ ]:
mapping = {
    "moong": "mungbean",
    "urad": "blackgram",
    "masoor": "lentil",
    "tur": "pigeonpeas",
    "gram": "chickpea",
    "groundnut": "groundnut",  # already fine after space removal
    "jowar": "millet"
}
df_fert["Crop"] = df_fert["Crop"].replace(mapping)

In [ ]:
print(df_fert.columns)

Index(['Soil_color', 'Nitrogen', 'Phosphorus', 'Potassium', 'pH', 'Rainfall',
       'Temperature', 'Crop', 'Fertilizer'],
      dtype='str')

In [ ]:
df_fert = df_fert.rename(columns={
    "Soil_color": "Soil",
    "pH": "PH",
    "Phosphorus": "Phosphorous"
})

In [ ]:
print(set(df_fert["Crop"].unique()))

{'mungbean', 'millet', 'rice', 'maize', 'soybean', 'cotton', 'turmeric', 'blackgram', 'grapes', 'groundnut', 'lentil', 'sugarcane', 'pigeonpeas', 'wheat', 'ginger', 'chickpea'}

In [ ]:
df_fert = df_fert[df_fert["Crop"].isin([
    'rice','maize','blackgram','cotton','chickpea','sugarcane',
    'lentil','millet','grapes','pigeonpeas','groundnut','mungbean','wheat'
])]

In [ ]:
df_fert["Soil"] = (
    df_fert["Soil"]
    .str.strip()
    .str.lower()
)

# mapping
soil_mapping = {
    "black": "Alkaline",
    "red": "Acidic",
    "dark brown": "Peaty",
    "medium brown": "Loamy",
    "light brown": "Neutral",
    "reddish brown": "Acidic"
}

# apply mapping safely
df_fert["Soil"] = df_fert["Soil"].map(soil_mapping).fillna(df_fert["Soil"])

In [ ]:
df_fert["Soil"].unique()

NameError: name 'df_fert' is not defined

In [ ]:
df_fert.head()

,Soil,Nitrogen,Phosphorous,Potassium,PH,Rainfall,Temperature,Crop,Fertilizer
0,Alkaline,75,50,100,6.5,1000,20,sugarcane,Urea
1,Alkaline,80,50,100,6.5,1000,20,sugarcane,Urea
2,Alkaline,85,50,100,6.5,1000,20,sugarcane,Urea
3,Alkaline,90,50,100,6.5,1000,20,sugarcane,Urea
4,Alkaline,95,50,100,6.5,1000,20,sugarcane,Urea

In [ ]:
df_fert["Crop"] = df_fert["Crop"].replace("rice", "paddy")

In [ ]:
    # split
X_fert = df_fert.drop("Fertilizer", axis=1)
y_fert = df_fert["Fertilizer"]

# encode categorical columns
X_fert = pd.get_dummies(X_fert, columns=["Soil", "Crop"])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X_fert, 
    y_fert, 
    test_size=0.2, 
    random_state=42,
    stratify=y_fert
)

In [ ]:
rf_fert = RandomForestClassifier(n_estimators=100, random_state=42,class_weight="balanced")
rf_fert.fit(X_train, y_train)
y_pred = rf_fert.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score

# Accuracy (you already trained rf_fert)
y_pred = rf_fert.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))

Test Accuracy: 0.9335664335664335